[dependencies]

[package]
cjc-version = "0.53.4"
compile-option = "-O2"
description = "(Cangjie) Coloring terminal so simple you already know how to do it !"
link-option = ""
name = "terminalcolor"
output-type = "static"
src-dir = ""
target-dir = ""
version = "0.0.4"
package-configuration = {}
